export const loginUser = {
    LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
    LOGIN_USER_SUCCESSFUL: 'LOGIN_USER_SUCCESSFUL',
    LOGIN_USER_FAILED: 'LOGIN_USER_FAILED',
    LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS'
}

export const getUserTodos = {
    GET_USER_TODOS_REQUEST: 'GET_USER_TODOS_REQUEST',
    GET_USER_TODOS_SUCCESS: 'GET_USER_TODOS_SUCCESS',
    GET_USER_TODOS_FAILED: 'GET_USER_TODOS_FAILED',
    ADD_TITLE_SUCCESS: 'ADD_TITLE_SUCCESS',
    ADD_TODOBODY_SUCCESS: 'ADD_TODOBODY_SUCCESS',
    DELETE_TODOBODY_SUCCESS: 'DELETE_TODOBODY_SUCCESS',
    SHARE_TASK_SUCCESS: 'SHARE_TASK_SUCCESS',
    AUTHORIZE_USER_SUCCESS: 'AUTHORIZE_USER_SUCCESS'
}

export const otherTodos = {
    OTHERS_TODO_REQUEST: 'OTHERS_TODO_REQUEST',
    OTHERS_TODO_SUCCESS: 'OTHERS_TODO_SUCCESS',
    OTHERS_TODO_FAILED: 'OTHERS_TODO_FAILED',
    CLEAR_TODO_SUCCESS: 'CLEAR_TODO_SUCCESS'
}